> /Users/athmajanvivekananthan/WCE/JEPA - MARL/multi-agent/iDQN/bert_5050_mode20/bertsekas-marl/learn_idqn_CE.py(234)retrieveRandomFromMongo()
    233             import ipdb; ipdb.set_trace()
--> 234             x = np.array(doc["obs"][0:10], dtype=np.float32)
    235             prev_actions = np.array(doc["obs"][-10:][0:5], dtype=np.float32)
{'_id': ObjectId('66e89a9e27330a1493e2c7dc'), 'obs': [0.5555555820465088, 0.8888888955116272, 0.5555555820465088, 0.3333333432674408, 0.4444444477558136, 0.4444444477558136, 0.4444444477558136, 0.6666666865348816, 1.0, 1.0], 'qval': [-7.699999809265137, -7.699999809265137, -7.260000228881836, -6.639999866485596, -8.380000114440918], 'prev_qvals': [-7.679999828338623, -6.800000190734863, -6.059999942779541, -6.679999828338623, -8.579999923706055]}
Traceback (most recent call last):
  File "/Users/athmajanvivekananthan/WCE/JEPA - MARL/multi-agent/iDQN/bert_5050_mode20/bertsekas-marl/learn_idqn_CE.py", line 360, in <module>
  File "/Users/athmajanvivekananthan/WCE/JEPA - MARL/multi-agent/iDQN/bert_5050_mode20/bertsekas-marl/learn_idqn_CE.py", line 234, in retrieveRandomFromMongo
    collection = db[f'mode_20_Q_Agent{agentID}']
               ^^
  File "/Users/athmajanvivekananthan/miniconda3/lib/python3.11/bdb.py", line 90, in trace_dispatch
    return self.dispatch_line(frame)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/athmajanvivekananthan/miniconda3/lib/python3.11/bdb.py", line 115, in dispatch_line
    if self.quitting: raise BdbQuit
                      ^^^^^^^^^^^^^
bdb.BdbQuit
If you suspect this is an IPython 8.26.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org
You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.
Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True