> /Users/athmajanvivekananthan/WCE/JEPA - MARL/multi-agent/PPO/bert_marl/mode20-dqn/dqn_seq.py(267)<module>()
    266                     import ipdb; ipdb.set_trace()
--> 267                     prev_actions[i]  = action.detach().item()
    268
tensor([3, 0])
[Discrete(5), Discrete(5)]
Discrete(5)
2
Traceback (most recent call last):
  File "/Users/athmajanvivekananthan/WCE/JEPA - MARL/multi-agent/PPO/bert_marl/mode20-dqn/dqn_seq.py", line 267, in <module>
    prev_actions[i]  = action.detach().item()
                       ^^^^^^
  File "/Users/athmajanvivekananthan/miniconda3/lib/python3.11/bdb.py", line 90, in trace_dispatch
    return self.dispatch_line(frame)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/athmajanvivekananthan/miniconda3/lib/python3.11/bdb.py", line 115, in dispatch_line
    if self.quitting: raise BdbQuit
                      ^^^^^^^^^^^^^
bdb.BdbQuit
If you suspect this is an IPython 8.26.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org
You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.
Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True